version: 2
sphinx:
  configuration: docs/source/conf.py
formats: all
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --without dev,tests
